### ISSUE TITLE
(ms-product) Packaging

### ISSUE THREAD

**Issue by Kybox** [vyjorg/LPDM#1]
@VianneyDiris 
Le MS product devrait packager en JAR

https://github.com/vyjorg/LPDM/blob/9c61a63ca312d300bba4bb937553a1d2f53df861/src/ms-product/pom.xml#L9

**Comment by VianneyDiris** [comment]
le packaging a été mis en jar sur ms-product sur la branche develop/msproduct et ms-stock sur la branche develop/msstock
